/*
 * Template Bank — compositional post generation system.
 *
 * Instead of hardcoded full-post templates, we combine:
 *   HOOK × BODY × CLOSER
 *
 * Each context type has its own component banks.
 * 50 hooks × 50 bodies × 50 closers = 125,000 unique posts per context.
 * 8+ context types = 1,000,000+ unique combinations.
 *
 * A seed system ensures the same topic never produces the same post twice:
 * each generation call uses a random seed that shuffles component selection.
 *
 * No GPU. No LLM API. Pure deterministic combinatorial generation.
 */

"use strict";

// ---------------------------------------------------------------------------
// Context types — each gets its own component bank
// ---------------------------------------------------------------------------

const CONTEXTS = {
  milestone_building: {
    // "I just started my saas", "I launched my app", "I built a tool"
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nno funding. no team. just me.`,
      (t) => `${t}.\n\nscared and excited at the same time.`,
      (t) => `${t}.\n\nI have no idea what I'm doing.`,
      (t) => `${t}.\n\nday 1.`,
      (t) => `${t}.\n\nthis is either the best or worst decision I've ever made.`,
      (t) => `${t}.\n\nand nobody's talking about it.`,
      (t) => `${t}.\n\nI've been overthinking this for months.`,
      (t) => `${t}.\n\neveryone makes this look easy on here.`,
      (t) => `${t}.\n\nI don't have a plan.`,
      (t) => `${t}.\n\nmight fail. might work.`,
      (t) => `${t}.\n\nI've been thinking about this for way too long.`,
      (t) => `${t}.\n\nno investors. no safety net. just conviction.`,
      (t) => `${t}.\n\nI quit a stable job for this.`,
      (t) => `${t}.\n\nmy friends think I'm crazy.`,
      (t) => `${t}.\n\nmy family doesn't understand what I'm doing.`,
      (t) => `${t}.\n\nI'm building this from my bedroom.`,
      (t) => `${t}.\n\nzero revenue. zero users. zero excuses.`,
      (t) => `${t}.\n\nI'm going to build this in public.`,
      (t) => `${t}.\n\nbuilding this in public.`,
      (t) => `${t}.\n\nI'll share everything — the wins, the failures, the numbers.`,
      (t) => `${t}.\n\nraw process from day 1.`,
      (t) => `${t}.\n\nno hiding, no faking.`,
      (t) => `${t}.\n\nif you're building something too, drop what you're working on below.`,
      (t) => `${t}.\n\nwho else is building something right now?`,
      (t) => `${t}.\n\nany other founders out there?`,
      (t) => `${t}.\n\n6 months ago I was just thinking about it.`,
      (t) => `${t}.\n\nI've been planning this for a year.`,
      (t) => `${t}.\n\nturns out starting is the hardest part.`,
      (t) => `${t}.\n\nthe gap between thinking and doing is everything.`,
      (t) => `${t}.\n\nI'd rather try and fail than wonder what if.`,
      (t) => `${t}.\n\nthis is the scariest thing I've ever done.`,
      (t) => `${t}.\n\nbut also the most exciting.`,
      (t) => `${t}.\n\nI have a direction and a lot of caffeine.`,
      (t) => `${t}.\n\nwe'll figure the rest out.`,
      (t) => `${t}.\n\nscreenshot this. day 1 of many.`,
      (t) => `${t}.\n\nfollow along if you want to watch me build.`,
      (t) => `${t}.\n\nI'm documenting everything.`,
      (t) => `${t}.\n\nthe journey starts now.`,
      (t) => `${t}.\n\nlet's see how far I can take this.`,
      (t) => `${t}.\n\nI'm all in.`,
      (t) => `${t}.\n\nno backup plan.`,
      (t) => `${t}.\n\nthis is it.`,
      (t) => `${t}.\n\nI'm betting on myself.`,
      (t) => `${t}.\n\nworst case, I learn. best case, I win.`,
      (t) => `${t}.\n\nthe only way to know is to try.`,
      (t) => `${t}.\n\nI stopped planning and started doing.`,
      (t) => `${t}.\n\nperfectionism was killing me. so I just started.`,
      (t) => `${t}.\n\nI'm tired of watching other people do it.`,
      (t) => `${t}.\n\nit's my turn now.`,
      (t) => `${t}.\n\nlet's build.`,
    ],
    bodies: [
      "", // hook-only posts (short punchy)
      "but I'm doing it anyway.",
      "and honestly? it feels right.",
      "the fear is real. but so is the excitement.",
      "I'd rather fail at this than succeed at something I don't care about.",
      "most people never start. that's the only difference between them and me.",
      "the plan will change. the direction won't.",
      "I don't know where this goes. but I know I had to start.",
      "every expert was once a beginner who refused to quit.",
      "the market doesn't care about my feelings. neither do I.",
      "I'm not waiting for permission anymore.",
      "someone less qualified than you is doing it right now.",
      "the gap between people who start and people who don't is everything.",
      "I'll share the numbers, the mistakes, the wins — everything.",
      "if this helps one person start their own thing, worth it.",
      "building in public means accountability. that's the point.",
      "no hiding behind a polished brand. just raw process.",
      "the internet rewards people who ship. so I'm shipping.",
      "I'm not special. I just started.",
      "the hardest part wasn't building. it was deciding to build.",
      "I've been the person who 'has ideas' for years. now I'm the person who builds them.",
      "ideas are cheap. execution is everything. so I'm executing.",
      "I stopped consuming content about building and started building.",
      "the tutorials don't prepare you for this. nothing does.",
      "but I'd rather be confused and building than comfortable and watching.",
      "day 1 of building something I actually care about.",
      "let's see where this goes.",
      "the only guarantee is that I'll learn something.",
      "I'm not waiting for the perfect time. there isn't one.",
      "someone needed to see this today. maybe it's you.",
      "if you're on the fence about starting your own thing — do it.",
      "the worst that happens is I fail and learn. the best is everything.",
      "I'm building this for the person I was 6 months ago.",
      "no more 'someday.' someday is today.",
      "the difference between dreamers and builders is one decision.",
      "I made that decision today.",
      "follow along. or don't. I'm building either way.",
      "I'll post updates every week. wins, losses, numbers, everything.",
      "this is either the beginning of something great or a expensive lesson.",
      "either way, I'm growing.",
      "the only thing worse than failing is not trying.",
      "I see people on here building amazing things. I want to be one of them.",
      "so I'm starting. today. right now.",
      "no more excuses. no more delays. just building.",
      "I've been the audience for too long. time to be the creator.",
      "the world doesn't need another watcher. it needs more builders.",
      "I don't have all the answers. but I have the first one: start.",
      "everything after this is just figuring it out as I go.",
      "and that's okay.",
      "the best builders I know didn't have a plan either. they just started.",
      // Outcome-focused bodies — what the user gets from this
      "the goal: replace my income within 12 months.",
      "the goal: 100 users in 90 days. then 1000. then 10,000.",
      "the goal: never work for someone else again.",
      "the outcome I'm chasing: freedom to work on what I want, when I want.",
      "the outcome: a product that makes people's lives easier.",
      "the outcome: proof that I can build something people pay for.",
      "the outcome: waking up excited to work. every single day.",
      "the outcome: a business that runs without me eventually.",
      "the outcome: financial independence. not riches. just freedom.",
      "the outcome: showing my kids that building beats working for someone else.",
      "the outcome: a portfolio of things I built, not a resume of things I did for others.",
      "the outcome: being able to say 'I built that.'",
      "the outcome: customers who love what I made.",
      "the outcome: revenue that covers my life. everything after that is bonus.",
      "the outcome: proving the doubters wrong. including the one in my head.",
      "the outcome: a system that compounds while I sleep.",
      "the outcome: never having to ask permission to ship something again.",
      "the outcome: building the tool I wish existed.",
      "the outcome: solving a real problem for real people.",
      "the outcome: a business I'm proud to put my name on.",
    ],
    closers: [
      "",
      "let's see how far I can take this.",
      "here we go.",
      "let's build.",
      "wish me luck.",
      "let's see what happens.",
      "day 1 of many.",
      "follow along if you want to watch.",
      "screenshot this. let's check back in 6 months.",
      "I'm all in.",
      "no backup plan.",
      "this is it.",
      "I'm betting on myself.",
      "let's go.",
      "the journey starts now.",
      "join me if you're building something too.",
      "drop what you're working on below.",
      "reply with what you're building.",
      "let's hold each other accountable.",
      "who's with me?",
      "follow for updates.",
      "I'll post weekly updates.",
      "stay tuned.",
      "this is just the beginning.",
      "watch me.",
      "or don't. I'm building either way.",
      "let's see where this goes.",
      "the only guarantee is I'll learn something.",
      "worst case, I learn. best case, I win.",
      "either way, I'm growing.",
      "on to the next step.",
      "one day at a time.",
      "brick by brick.",
      "the foundation is laid.",
      "now the real work begins.",
      "I'll share everything — wins, losses, numbers.",
      "no hiding. no faking. raw process.",
      "if this helps one person start, worth it.",
      "someone needed to see this today.",
      "maybe it's you.",
      "your turn.",
      "what are you waiting for?",
      "stop planning. start building.",
      "the world needs more builders.",
      "be one.",
      "I'm not special. I just started.",
      "you can too.",
      "the hardest part is deciding.",
      "decide.",
      "then do.",
    ],
  },

  milestone_consuming: {
    // "I started a new show", "I started reading a book", "I started watching anime"
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nand I already know it's going to ruin my sleep schedule.`,
      (t) => `${t}.\n\nmy productivity is about to drop to zero.`,
      (t) => `${t}.\n\nsay goodbye to my free time.`,
      (t) => `${t}.\n\nI'm already 3 episodes in.`,
      (t) => `${t}.\n\nand I have no self-control.`,
      (t) => `${t}.\n\nthis is going to consume my entire week.`,
      (t) => `${t}.\n\nwhy do I do this to myself.`,
      (t) => `${t}.\n\nI told myself I'd watch one episode.`,
      (t) => `${t}.\n\nthat was 4 hours ago.`,
      (t) => `${t}.\n\nmy sleep schedule is about to be destroyed.`,
      (t) => `${t}.\n\nand I have zero regrets.`,
      (t) => `${t}.\n\nthis is my personality now.`,
      (t) => `${t}.\n\nI'm not okay.`,
      (t) => `${t}.\n\nand it's only episode 1.`,
      (t) => `${t}.\n\nI can already tell this is going to be a problem.`,
      (t) => `${t}.\n\nmy brain has been hijacked.`,
      (t) => `${t}.\n\nI have things to do today. but this.`,
      (t) => `${t}.\n\nand just like that, my weekend is gone.`,
      (t) => `${t}.\n\nI blame everyone who recommended it.`,
      (t) => `${t}.\n\nwhy did I wait so long to start this.`,
      (t) => `${t}.\n\nI'm hooked.`,
      (t) => `${t}.\n\nthis is a problem.`,
      (t) => `${t}.\n\na good problem.`,
      (t) => `${t}.\n\nI'm not going to be productive for a while.`,
      (t) => `${t}.\n\neveryone who told me to watch this was right.`,
      (t) => `${t}.\n\nI should have listened sooner.`,
      (t) => `${t}.\n\nmy brain: you have work tomorrow.\nme: one more episode.`,
      (t) => `${t}.\n\nI have no self-control and I know it.`,
      (t) => `${t}.\n\nthis is the best bad decision I've made all week.`,
      (t) => `${t}.\n\nI'm going to lose so much sleep over this.`,
      (t) => `${t}.\n\nand I don't care.`,
      (t) => `${t}.\n\nmy responsibilities are calling. I'm ignoring them.`,
      (t) => `${t}.\n\nthis is my life now.`,
      (t) => `${t}.\n\nI came in with low expectations. I was wrong.`,
      (t) => `${t}.\n\nI'm in too deep already.`,
      (t) => `${t}.\n\nthere's no going back.`,
      (t) => `${t}.\n\nI can't stop.`,
      (t) => `${t}.\n\nI won't stop.`,
      (t) => `${t}.\n\ndon't let me start another one after this.`,
      (t) => `${t}.\n\nmy to-do list is crying.`,
      (t) => `${t}.\n\nI'll deal with responsibilities later.`,
      (t) => `${t}.\n\nright now, this is more important.`,
      (t) => `${t}.\n\nI regret nothing.`,
      (t) => `${t}.\n\nthis is what happiness feels like.`,
      (t) => `${t}.\n\nI've found my new obsession.`,
      (t) => `${t}.\n\nmy free time belongs to this now.`,
      (t) => `${t}.\n\nI'm not accepting calls at this time.`,
      (t) => `${t}.\n\nplease don't distract me.`,
      (t) => `${t}.\n\nthis is my hyperfixation era.`,
    ],
    bodies: [
      "",
      "one more episode. that's what I keep telling myself.",
      "I'll sleep when it's over.",
      "my brain says stop. my body says one more.",
      "the plot is too good to pause.",
      "I came for one episode. I stayed for the whole season.",
      "I told myself I'd pace it. I lied.",
      "there's no pacing something this good.",
      "I should be working. but this exists. so.",
      "my productivity was nice while it lasted.",
      "I'll be productive tomorrow. probably.",
      "the characters have my full attention now.",
      "I'm emotionally invested and it's only been 2 hours.",
      "I already know the ending will destroy me.",
      "but I'm not stopping.",
      "I've made my peace with the sleep I'm about to lose.",
      "this is self-care. I've decided.",
      "sometimes you need to turn your brain off and just watch.",
      "this is my therapy now.",
      "I don't need a therapist. I need season 2.",
      "the soundtrack alone is worth it.",
      "I'm already recommending it to everyone I know.",
      "if you haven't seen it yet, what are you doing.",
      "I'm late to the party but I'm here now.",
      "better late than never.",
      "I understand the hype now.",
      "I get it. I finally get it.",
      "everyone was right about this one.",
      "I should have started this months ago.",
      "no spoilers. I'm going in blind.",
      "and it's already exceeding expectations.",
      "the first episode had me hooked.",
      "I can already tell this is going to be top 5.",
      "my ranking is already shifting.",
      "I've found my new favorite.",
      "this is going on the list.",
      "the all-time list.",
      "I'm not ready for it to end.",
      "so I'm savoring every episode.",
      "okay no I'm binging it. who am I kidding.",
      "I tried to savor it. I failed.",
      "the binge is inevitable.",
      "resistance is futile.",
      "I've accepted my fate.",
      "my weekends are booked for the foreseeable future.",
      "if you need me, I'm busy. permanently.",
      "I have entered my era of no free time.",
      "and I'm loving every second of it.",
      "this is the best thing I've done for myself all week.",
      "no regrets. just episodes.",
    ],
    closers: [
      "",
      "send help.",
      "and snacks.",
      "I'll surface in a few days.",
      "don't wait up.",
      "I'll be fine. probably.",
      "wish me luck.",
      "I'm going to need it.",
      "my sleep schedule is already gone.",
      "RIP my productivity.",
      "RIP my free time.",
      "RIP my sleep.",
      "I regret nothing.",
      "this is a judgment-free zone.",
      "don't judge me.",
      "I'm happy. leave me alone.",
      "this is self-care.",
      "I've decided.",
      "no notes.",
      "10/10 would binge again.",
      "already recommending it.",
      "what should I watch next?",
      "drop your recs below.",
      "what else am I missing?",
      "I'm open to suggestions.",
      "but only after I finish this.",
      "which won't be anytime soon.",
      "I'm committed now.",
      "no going back.",
      "I'm in too deep.",
      "the hyperfixation has begun.",
      "pray for my sleep schedule.",
      "pray for my productivity.",
      "pray for me.",
      "I'll be okay. eventually.",
      "right now? not okay. in a good way.",
      "this is my life now.",
      "and I'm not mad about it.",
      "actually I'm thrilled.",
      "this is the content I needed.",
      "thank me later.",
      "or thank the person who recommended it to me.",
      "either way.",
      "go watch it.",
      "do it.",
      "you won't regret it.",
      "unless you value sleep.",
      "then you will.",
      "but do it anyway.",
      "one of us.",
    ],
  },

  milestone_habit: {
    // "I started going to the gym", "I started meditating", "I started journaling"
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nday 1.`,
      (t) => `${t}.\n\nand I already feel different.`,
      (t) => `${t}.\n\nlet's see how long this lasts.`,
      (t) => `${t}.\n\nthis time it's different. I think.`,
      (t) => `${t}.\n\nI've said this before. but this time I mean it.`,
      (t) => `${t}.\n\nno more excuses.`,
      (t) => `${t}.\n\nI'm done waiting for motivation.`,
      (t) => `${t}.\n\ndiscipline > motivation.`,
      (t) => `${t}.\n\nthe hardest part is showing up.`,
      (t) => `${t}.\n\nand I showed up today.`,
      (t) => `${t}.\n\nsmall steps. big changes.`,
      (t) => `${t}.\n\nconsistency is the only secret.`,
      (t) => `${t}.\n\nI'm not trying to be perfect. just consistent.`,
      (t) => `${t}.\n\nevery expert was once a beginner.`,
      (t) => `${t}.\n\nI'm starting from zero. again.`,
      (t) => `${t}.\n\nbut zero is better than negative.`,
      (t) => `${t}.\n\nthe version of me a year from now will thank me.`,
      (t) => `${t}.\n\nor at least I hope so.`,
      (t) => `${t}.\n\nI'm tired of being the person who 'is going to start.'`,
      (t) => `${t}.\n\nso I started.`,
      (t) => `${t}.\n\nno announcement. no hype. just doing it.`,
      (t) => `${t}.\n\nthe best time to start was a year ago. the second best is now.`,
      (t) => `${t}.\n\nI've been 'about to start' for 6 months.`,
      (t) => `${t}.\n\ntoday I actually did it.`,
      (t) => `${t}.\n\nmotivation is fleeting. discipline is forever.`,
      (t) => `${t}.\n\nI don't feel like it. I'm doing it anyway.`,
      (t) => `${t}.\n\nthat's the whole secret.`,
      (t) => `${t}.\n\nI've failed at this before.`,
      (t) => `${t}.\n\nbut failing and quitting are different things.`,
      (t) => `${t}.\n\nI failed. I'm back.`,
      (t) => `${t}.\n\nevery day is day 1.`,
      (t) => `${t}.\n\nthe streak starts today.`,
      (t) => `${t}.\n\nI'm building a system, not relying on willpower.`,
      (t) => `${t}.\n\nwillpower runs out. systems don't.`,
      (t) => `${t}.\n\nI'm not waiting for Monday.`,
      (t) => `${t}.\n\nor the new year.`,
      (t) => `${t}.\n\nor the perfect moment.`,
      (t) => `${t}.\n\nthere is no perfect moment.`,
      (t) => `${t}.\n\nI'm not special. I just started.`,
      (t) => `${t}.\n\nand starting is the hardest part.`,
      (t) => `${t}.\n\nI know because I've avoided it for months.`,
      (t) => `${t}.\n\nthe resistance is real. so is the decision to push through it.`,
      (t) => `${t}.\n\nI'd rather be a beginner than a spectator.`,
      (t) => `${t}.\n\nthe only difference between me and the people I admire is they started.`,
      (t) => `${t}.\n\nso I'm starting.`,
      (t) => `${t}.\n\nno more watching from the sidelines.`,
      (t) => `${t}.\n\nit's my turn.`,
      (t) => `${t}.\n\nday 1. again. but for real this time.`,
      (t) => `${t}.\n\nlet's go.`,
    ],
    bodies: [
      "",
      "the first day is always the hardest.",
      "but I showed up. that's the win.",
      "tomorrow I might not want to. I'll show up anyway.",
      "the secret isn't motivation. it's showing up when you don't have any.",
      "I don't need to be perfect. I need to be consistent.",
      "1% better every day. that's the goal.",
      "small habits compound. that's the whole game.",
      "I'm not trying to transform overnight. I'm trying to not quit.",
      "the people who succeed aren't the ones who are motivated. they're the ones who don't stop.",
      "I've started and stopped this 10 times before.",
      "but 11 is my lucky number.",
      "the difference this time? I'm not waiting to feel ready.",
      "I'll never feel ready. so I'm starting unready.",
      "the bar is low: just don't quit.",
      "I can do that.",
      "I've been the person who talks about starting for years.",
      "now I'm the person who started.",
      "it's a small shift. but it changes everything.",
      "the version of me in 6 months is built today.",
      "every day I show up is a vote for who I want to become.",
      "I'm casting my vote today.",
      "motivation gets you started. discipline keeps you going.",
      "I'm past the motivation phase. now it's just work.",
      "and I'm okay with that.",
      "the grind isn't glamorous. but it works.",
      "I'll post updates. not for clout. for accountability.",
      "if I post it, I have to do it.",
      "so I'm posting it.",
      "the internet is my accountability partner now.",
      "I've failed at this enough times to know what doesn't work.",
      "this time I'm building a system, not relying on vibes.",
      "systems > goals. goals fade. systems compound.",
      "I'm building a system today.",
      "the first rep is always the worst.",
      "but you can't get to the 100th rep without it.",
      "I'm doing rep #1.",
      "and it feels terrible. and that's fine.",
      "feeling terrible is not a reason to stop.",
      "it's a sign you're doing something new.",
      "and new is where growth happens.",
      "I'm not chasing a result. I'm chasing consistency.",
      "results follow consistency. always.",
      "I've been inconsistent my whole life.",
      "time to change that.",
      "one day at a time. no big promises.",
      "just today. and then tomorrow. and then the next day.",
      "that's it. that's the plan.",
      "simple doesn't mean easy.",
      "but it means doable.",
    ],
    closers: [
      "",
      "day 1 of many.",
      "the streak starts now.",
      "check back in 30 days.",
      "screenshot this. let's see where I am in 6 months.",
      "I'll post updates weekly.",
      "follow along if you're on your own journey.",
      "who else is starting something new?",
      "drop your habit below. let's keep each other accountable.",
      "your turn.",
      "what are you waiting for?",
      "start today.",
      "not monday. today.",
      "the best time was yesterday. the second best is now.",
      "no more excuses.",
      "let's go.",
      "one day at a time.",
      "brick by brick.",
      "1% better.",
      "consistency is the only secret.",
      "show up.",
      "that's it. that's the whole post.",
      "I'm not special. I just started.",
      "you can too.",
      "the hardest part is deciding.",
      "decide.",
      "then do.",
      "I'm rooting for you too.",
      "we're in this together.",
      "let's build something worth having.",
      "day 1.",
      "again.",
      "but for real this time.",
      "no more watching from the sidelines.",
      "it's my turn.",
      "and yours.",
      "start.",
      "now.",
      "not tomorrow. not monday. now.",
      "I'll be here tomorrow. will you?",
      "the only failure is quitting.",
      "I'm not quitting.",
      "see you on day 365.",
      "or day 2. whichever comes first.",
      "spoiler: day 2 comes first.",
      "and I'll be there.",
      "consistency > intensity.",
      "always.",
      "small steps. big changes.",
      "trust the process.",
    ],
  },

  milestone_career: {
    // "I started a new job", "I got a promotion", "I quit my job"
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nnew chapter.`,
      (t) => `${t}.\n\nand it hasn't fully sunk in yet.`,
      (t) => `${t}.\n\nI've been waiting for this for a long time.`,
      (t) => `${t}.\n\nsurreal.`,
      (t) => `${t}.\n\ngrateful. nervous. excited. all at once.`,
      (t) => `${t}.\n\nthe imposter syndrome is already kicking in.`,
      (t) => `${t}.\n\nbut I belong here. I keep reminding myself.`,
      (t) => `${t}.\n\nI almost didn't apply.`,
      (t) => `${t}.\n\nglad I did.`,
      (t) => `${t}.\n\nthe version of me a year ago wouldn't believe this.`,
      (t) => `${t}.\n\nhard work pays off. cliché but true.`,
      (t) => `${t}.\n\nI'm not where I want to be. but I'm not where I was.`,
      (t) => `${t}.\n\nthis is a step. not the destination.`,
      (t) => `${t}.\n\nnew role. same hunger.`,
      (t) => `${t}.\n\nthe real work starts now.`,
      (t) => `${t}.\n\nI have a lot to learn.`,
      (t) => `${t}.\n\nand I'm ready to learn it.`,
      (t) => `${t}.\n\nthank you to everyone who supported me.`,
      (t) => `${t}.\n\nand to everyone who doubted me — thanks too.`,
      (t) => `${t}.\n\nthe doubt was fuel.`,
      (t) => `${t}.\n\nI'm stepping into unfamiliar territory.`,
      (t) => `${t}.\n\nthat's exactly where growth happens.`,
      (t) => `${t}.\n\ncomfortable doesn't grow you.`,
      (t) => `${t}.\n\nI was comfortable for too long.`,
      (t) => `${t}.\n\ntime to be uncomfortable.`,
      (t) => `${t}.\n\nI left comfort for uncertainty.`,
      (t) => `${t}.\n\nbest trade I've ever made.`,
      (t) => `${t}.\n\nnew environment. new challenges. new growth.`,
      (t) => `${t}.\n\nI'm the newest person in the room again.`,
      (t) => `${t}.\n\nhumble beginnings, round 2.`,
      (t) => `${t}.\n\nI have everything to prove.`,
      (t) => `${t}.\n\nand nothing to lose.`,
      (t) => `${t}.\n\nthe pressure is real. so is the opportunity.`,
      (t) => `${t}.\n\nI'm going to give it everything.`,
      (t) => `${t}.\n\nthis is what I've been working toward.`,
      (t) => `${t}.\n\nand now that it's here, the work really begins.`,
      (t) => `${t}.\n\nday 1 of the next chapter.`,
      (t) => `${t}.\n\nlet's get to work.`,
      (t) => `${t}.\n\nI earned this. but I'm not done earning.`,
      (t) => `${t}.\n\nthe ceiling just got higher.`,
      (t) => `${t}.\n\ngood. I like climbing.`,
      (t) => `${t}.\n\nI'm the youngest/least experienced person here.`,
      (t) => `${t}.\n\nperfect. that means the most room to grow.`,
      (t) => `${t}.\n\nI have a lot to learn. and I will.`,
      (t) => `${t}.\n\nwatch me.`,
      (t) => `${t}.\n\nthis is just the beginning.`,
      (t) => `${t}.\n\nthe best is yet to come.`,
      (t) => `${t}.\n\nonward.`,
    ],
    bodies: [
      "",
      "the imposter syndrome is loud right now.",
      "but I've learned that imposter syndrome means you're growing.",
      "and growing is the whole point.",
      "I have so much to learn.",
      "but I've always been a fast learner.",
      "the first 90 days are about listening, not proving.",
      "I'm going to listen hard and work harder.",
      "new team. new culture. new expectations.",
      "I'm walking in with humility and hunger.",
      "I left a role where I was comfortable.",
      "comfortable is dangerous. it makes you stop growing.",
      "I'd rather be uncomfortable and growing than comfortable and stagnant.",
      "the people who helped me get here know who they are.",
      "I'm grateful for every mentor, every advocate, every person who took a chance on me.",
      "this isn't just my win. it's theirs too.",
      "but the work isn't done. it's just starting.",
      "new title. same work ethic.",
      "actually, harder work ethic. the stakes are higher.",
      "and I'm ready for it.",
      "I almost talked myself out of applying.",
      "'you're not ready.' 'you don't have enough experience.' 'they'll see through you.'",
      "I applied anyway.",
      "best decision I made this year.",
      "if you're on the fence about applying for something — do it.",
      "the worst they can say is no. and no is just information.",
      "I've been the youngest/inexperienced one before.",
      "I caught up then. I'll catch up now.",
      "the learning curve is steep. but I've climbed steep before.",
      "give me 90 days. I'll be up to speed.",
      "give me a year. I'll be leading.",
      "I'm not arrogant. I'm just confident in my ability to learn.",
      "there's a difference.",
      "the real work starts on day 1. not the offer. not the announcement. day 1.",
      "and day 1 is tomorrow.",
      "I'm nervous. genuinely nervous.",
      "but nervous and excited feel the same in your body.",
      "so I'm choosing to call it excited.",
      "new challenges. new problems. new growth.",
      "that's the whole point of a career. not comfort. growth.",
      "I was comfortable for 2 years. it was nice. I didn't grow.",
      "now I'm uncomfortable. and I'm growing already.",
      "the best career moves are the ones that scare you a little.",
      "this one scares me. that's how I know it's right.",
      "I'm stepping into a role I'm not 100% ready for.",
      "nobody is ever 100% ready. that's the secret.",
      "you grow into the role, not before it.",
      "I'm growing now.",
      "thank you to everyone who believed in me before I believed in myself.",
      "I'll make you proud.",
    ],
    closers: [
      "",
      "let's get to work.",
      "the real work starts now.",
      "day 1 of the next chapter.",
      "onward.",
      "upward.",
      "this is just the beginning.",
      "the best is yet to come.",
      "watch me.",
      "I'm ready.",
      "let's go.",
      "new chapter. same hunger.",
      "grateful. hungry. ready.",
      "thank you. now back to work.",
      "I earned this. now I'll earn the next one.",
      "the ceiling just got higher.",
      "good. I like climbing.",
      "I have everything to prove.",
      "and nothing to lose.",
      "this is what I've been working toward.",
      "and now that it's here, the work really begins.",
      "no complacency.",
      "no settling.",
      "just growth.",
      "if you're thinking about a career move — do it.",
      "the worst case is you learn something.",
      "the best case is everything changes.",
      "your turn.",
      "what are you waiting for?",
      "the comfort zone is a trap.",
      "I escaped.",
      "you can too.",
      "apply. even if you're not ready.",
      "especially if you're not ready.",
      "that's where the growth is.",
      "I'm proof.",
      "day 1 is tomorrow.",
      "I'll be there.",
      "early.",
      "always.",
      "the new kid on the block.",
      "but not for long.",
      "give me 90 days.",
      "I'll be up to speed.",
      "give me a year.",
      "I'll be leading.",
      "humble. hungry. ready.",
      "that's the whole post.",
      "onward and upward.",
    ],
  },

  milestone_content: {
    // "I started a youtube channel", "I started posting on tiktok"
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nfirst post. let's go.`,
      (t) => `${t}.\n\nand I'm terrified.`,
      (t) => `${t}.\n\nzero followers. zero views. zero excuses.`,
      (t) => `${t}.\n\nI'm starting from nothing.`,
      (t) => `${t}.\n\neveryone starts at zero.`,
      (t) => `${t}.\n\nthis is my zero.`,
      (t) => `${t}.\n\nI've been watching other people do it for years.`,
      (t) => `${t}.\n\nnow it's my turn.`,
      (t) => `${t}.\n\nI've been the audience for too long.`,
      (t) => `${t}.\n\ntime to be the creator.`,
      (t) => `${t}.\n\nthe world doesn't need another watcher.`,
      (t) => `${t}.\n\nso I'm creating.`,
      (t) => `${t}.\n\nI have no idea what I'm doing.`,
      (t) => `${t}.\n\nbut I'm doing it anyway.`,
      (t) => `${t}.\n\nthe first post is the hardest.`,
      (t) => `${t}.\n\nso here it is.`,
      (t) => `${t}.\n\nI've been planning this for months.`,
      (t) => `${t}.\n\nplanning is just procrastination with a fancy name.`,
      (t) => `${t}.\n\nso I stopped planning and started posting.`,
      (t) => `${t}.\n\nno more 'someday.'`,
      (t) => `${t}.\n\nsomeday is today.`,
      (t) => `${t}.\n\nI'm not waiting for the perfect setup.`,
      (t) => `${t}.\n\nor the perfect idea.`,
      (t) => `${t}.\n\nor the perfect time.`,
      (t) => `${t}.\n\nperfect doesn't exist. posted does.`,
      (t) => `${t}.\n\nI'd rather post something imperfect than nothing at all.`,
      (t) => `${t}.\n\nconsistency > quality. at least at first.`,
      (t) => `${t}.\n\nI'll get better by posting, not by planning.`,
      (t) => `${t}.\n\nthis is post #1.`,
      (t) => `${t}.\n\nI'm aiming for 100.`,
      (t) => `${t}.\n\none down. 99 to go.`,
      (t) => `${t}.\n\nfollow along if you want to watch me figure this out.`,
      (t) => `${t}.\n\nI'm building in public.`,
      (t) => `${t}.\n\nthe journey from 0 to 1000 starts with post #1.`,
      (t) => `${t}.\n\nthis is post #1.`,
      (t) => `${t}.\n\nI'm not trying to go viral.`,
      (t) => `${t}.\n\nI'm trying to be consistent.`,
      (t) => `${t}.\n\nvirality is luck. consistency is skill.`,
      (t) => `${t}.\n\nI'm building the skill.`,
      (t) => `${t}.\n\nmy content isn't great yet.`,
      (t) => `${t}.\n\nbut it will be. give me time.`,
      (t) => `${t}.\n\nthe only way to get good is to start bad.`,
      (t) => `${t}.\n\nand I'm starting bad.`,
      (t) => `${t}.\n\nproudly.`,
      (t) => `${t}.\n\nbecause bad is better than nothing.`,
      (t) => `${t}.\n\nand nothing is what I've been doing for years.`,
      (t) => `${t}.\n\nno more.`,
      (t) => `${t}.\n\nlet's go.`,
      (t) => `${t}.\n\npost #1 of many.`,
    ],
    bodies: [
      "",
      "I've been overthinking this for months.",
      "turns out the hardest part is hitting post.",
      "so I'm hitting it.",
      "the content isn't perfect. it never will be.",
      "but posted > perfect. always.",
      "I'm committing to posting every day for 30 days.",
      "not because I think it'll go viral.",
      "but because consistency is how you get good.",
      "and I want to get good.",
      "I've been consuming content for years.",
      "I know what good looks like. I just can't make it yet.",
      "but I will. by making bad stuff first.",
      "the gap between taste and skill is painful.",
      "I'm in the gap right now.",
      "but the only way through the gap is to keep making things.",
      "so I'm making things.",
      "I'm not waiting for confidence. I'm posting without it.",
      "confidence comes after action. not before.",
      "I learned that the hard way.",
      "if you're waiting to feel ready — stop waiting.",
      "you'll never feel ready. post anyway.",
      "the algorithm doesn't care about your feelings.",
      "neither do I. anymore.",
      "I'm posting for the person I was 6 months ago.",
      "the one who was too scared to start.",
      "if this helps one person hit post — worth it.",
      "I'm not special. I just hit post.",
      "you can too.",
      "the first 100 posts are practice.",
      "this is practice #1.",
      "I'm treating it as such.",
      "no pressure. just reps.",
      "the reps are the reward.",
      "I'll look back at this post in a year and cringe.",
      "that's the goal. cringing means I grew.",
      "if I'm not cringing at my old stuff, I'm not growing.",
      "so here's to future cringe.",
      "I'm starting from zero. no audience. no following. no clout.",
      "just me and the algorithm.",
      "let's see who wins.",
      "spoiler: the algorithm always wins. but I'll get some followers along the way.",
      "the goal isn't to go viral. it's to still be posting in a year.",
      "most people quit at 50 posts. I'm aiming for 500.",
      "the people who win aren't the best. they're the ones who didn't quit.",
      "I'm planning to not quit.",
      "we'll see.",
      "but that's the plan.",
      "post #1. here's to many more.",
      "let's see where this goes.",
    ],
    closers: [
      "",
      "follow along if you want to watch me grow.",
      "post #1 of many.",
      "one down. 99 to go.",
      "let's go.",
      "here's to post #1.",
      "the journey starts now.",
      "watch me figure this out.",
      "I'm building in public.",
      "no hiding. no faking. raw process.",
      "follow for updates.",
      "I'll post every day.",
      "or at least try to.",
      "consistency is the goal.",
      "not virality.",
      "not yet.",
      "first get consistent. then get good. then get viral.",
      "I'm at step 1.",
      "your turn.",
      "what are you waiting for?",
      "hit post.",
      "stop overthinking.",
      "hit post.",
      "the world needs more creators.",
      "be one.",
      "I'm not special. I just hit post.",
      "you can too.",
      "the hardest part is starting.",
      "I started.",
      "now it's your turn.",
      "screenshot this. let's check back in 6 months.",
      "I'll be here.",
      "posting.",
      "still.",
      "that's the whole point.",
      "consistency > everything.",
      "post #1.",
      "let's go.",
      "day 1.",
      "of many.",
      "the best time to start was a year ago.",
      "the second best is now.",
      "so I'm starting now.",
      "and you should too.",
      "hit post.",
      "do it.",
      "today.",
      "not tomorrow.",
      "today.",
      "I'll be here tomorrow too.",
      "will you?",
    ],
  },

  confession: {
    // "I failed at my startup", "I made $0", "I was wrong"
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nnot proud of it.`,
      (t) => `${t}.\n\nbut here's the truth.`,
      (t) => `${t}.\n\nI'm sharing this because nobody else does.`,
      (t) => `${t}.\n\neveryone posts the wins. nobody posts the losses.`,
      (t) => `${t}.\n\nthis is the post I wish I'd seen a year ago.`,
      (t) => `${t}.\n\nI almost didn't post this.`,
      (t) => `${t}.\n\nbut someone needs to hear it.`,
      (t) => `${t}.\n\nhere's what I learned from it.`,
      (t) => `${t}.\n\nthe lesson was expensive but worth it.`,
      (t) => `${t}.\n\nbiggest lesson:`,
      (t) => `${t}.\n\nhere's what it taught me:`,
      (t) => `${t}.\n\nit hurt. but it made me better.`,
      (t) => `${t}.\n\nI was wrong.`,
      (t) => `${t}.\n\nand I'm not afraid to admit it.`,
      (t) => `${t}.\n\nthis is embarrassing to share.`,
      (t) => `${t}.\n\nbut embarrassment is better than silence.`,
      (t) => `${t}.\n\nI wasted a lot of time on this.`,
      (t) => `${t}.\n\nbut wasted time isn't always wasted.`,
      (t) => `${t}.\n\nI failed. and that's okay.`,
      (t) => `${t}.\n\nfailure is data.`,
      (t) => `${t}.\n\nand I got a lot of data.`,
      (t) => `${t}.\n\nthe hard way.`,
      (t) => `${t}.\n\nI have no one to blame but myself.`,
      (t) => `${t}.\n\nand I'm not blaming anyone.`,
      (t) => `${t}.\n\nI own this.`,
      (t) => `${t}.\n\nno excuses.`,
      (t) => `${t}.\n\njust lessons.`,
      (t) => `${t}.\n\nif you're going through it right now — keep going.`,
      (t) => `${t}.\n\nI know how it feels.`,
      (t) => `${t}.\n\nit feels like the end. it's not.`,
      (t) => `${t}.\n\nit's a chapter. not the whole book.`,
      (t) => `${t}.\n\nthe pain is temporary. the lesson is permanent.`,
      (t) => `${t}.\n\nI'm sharing this so you don't make the same mistake.`,
      (t) => `${t}.\n\nlearn from my loss.`,
      (t) => `${t}.\n\nso my loss becomes your gain.`,
      (t) => `${t}.\n\nI've been pretending everything is fine.`,
      (t) => `${t}.\n\nit's not.`,
      (t) => `${t}.\n\nbut it will be.`,
      (t) => `${t}.\n\nthis is my accountability post.`,
      (t) => `${t}.\n\nI'm putting it out there so I can't hide from it.`,
      (t) => `${t}.\n\nthe truth sets you free. even when it's ugly.`,
      (t) => `${t}.\n\nand this is ugly.`,
      (t) => `${t}.\n\nbut freeing.`,
      (t) => `${t}.\n\nI'm starting over.`,
      (t) => `${t}.\n\nhumbled. wiser. still going.`,
      (t) => `${t}.\n\nthe comeback starts now.`,
      (t) => `${t}.\n\nhere's what nobody tells you about failing:`,
    ],
    bodies: [
      "",
      "the plan means nothing. execution is everything.",
      "I had the perfect plan. the plan didn't survive contact with reality.",
      "I spent months planning. weeks building. days watching it fail.",
      "the market doesn't care about your plan. it cares about value.",
      "I wasn't providing enough value. that's the hard truth.",
      "I was building something nobody asked for.",
      "the hardest lesson: your idea doesn't matter. their problem does.",
      "I was solving a problem I had. not a problem they had.",
      "big difference.",
      "I thought passion was enough. it's not.",
      "passion without execution is just enthusiasm.",
      "I thought I could outwork a bad strategy.",
      "you can't. I tried.",
      "the strategy was wrong. no amount of work fixes that.",
      "I should have talked to users sooner.",
      "I should have charged sooner.",
      "I should have launched sooner.",
      "I should have done a lot of things sooner.",
      "but 'should have' is useless. 'next time' is everything.",
      "next time, I'll talk to users first.",
      "next time, I'll charge from day 1.",
      "next time, I'll launch before I'm ready.",
      "the biggest mistake was waiting.",
      "I waited too long. the window closed.",
      "but windows reopen. and I'll be ready.",
      "I failed because I was afraid to fail.",
      "the irony is not lost on me.",
      "I played it safe. safe killed it.",
      "next time, I'm playing to win. not playing to not lose.",
      "those are different games.",
      "I was playing the wrong one.",
      "I learned more from this failure than from any success.",
      "success teaches you nothing. failure teaches you everything.",
      "this failure will make the next attempt work.",
      "I'm not done. I'm just getting started.",
      "the people who win are the ones who failed and kept going.",
      "I'm keeping going.",
      "if you're failing right now — you're in good company.",
      "every success story has a chapter like this.",
      "this is my chapter.",
      "the next chapter is the comeback.",
      "I'm not sharing this for sympathy.",
      "I'm sharing this because the internet only shows wins.",
      "and the wins are a small part of the story.",
      "the losses are where the growth happens.",
      "and I grew a lot.",
      "I'm better now than I was before this.",
      "not despite the failure. because of it.",
      "failure is the best teacher I've ever had.",
      "expensive tuition. but worth it.",
    ],
    closers: [
      "",
      "if this helps one person, worth it.",
      "sharing this so someone else doesn't make the same mistake.",
      "the process is the point.",
      "on to the next one.",
      "failure is part of the process.",
      "keep going.",
      "if you're going through it — keep going.",
      "it gets better.",
      "not overnight. but eventually.",
      "I'm proof.",
      "the comeback starts now.",
      "humbled. wiser. still going.",
      "I'm not done.",
      "not even close.",
      "lesson learned.",
      "tuition paid.",
      "moving on.",
      "the next attempt will be better.",
      "because I know what not to do now.",
      "sometimes you have to lose to learn how to win.",
      "I lost.",
      "now I'm learning to win.",
      "if you're failing — you're trying.",
      "and trying is the only way to eventually win.",
      "don't stop.",
      "I won't.",
      "the hard part isn't failing. it's starting again after.",
      "I'm starting again.",
      "watch me.",
      "this is not the end.",
      "it's the beginning of the comeback.",
      "stay tuned.",
      "the best revenge is massive success.",
      "I'm coming for it.",
      "your failures are not your identity.",
      "they're your education.",
      "I'm educated now.",
      "and ready.",
      "failure is data.",
      "I got a lot of data.",
      "now I'm building with it.",
      "the lesson was expensive. but I paid attention.",
      "and I'm not making the same mistake twice.",
      "on to the next.",
      "wiser. humbled. hungry.",
      "the comeback is always stronger than the setback.",
      "I'm counting on that.",
      "if this helped you — share it.",
      "someone else needs to see it too.",
    ],
  },

  opinion: {
    // "X is better than Y", "X is the greatest", "X is overrated"
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nI said what I said.`,
      (t) => `${t}.\n\nand I'm tired of pretending it's not true.`,
      (t) => `${t}.\n\nnobody wants to hear it but it's facts.`,
      (t) => `${t}.\n\neveryone knows it. nobody wants to admit it.`,
      (t) => `unpopular opinion:\n\n${t}.`,
      (t) => `hot take:\n\n${t}.`,
      (t) => `${t}.\n\nchange my mind.`,
      (t) => `${t}.\n\nagree or disagree?`,
      (t) => `${t}.\n\nI'll wait.`,
      (t) => `${t}.\n\nscreenshot this in 6 months.`,
      (t) => `${t}.\n\nwho disagrees?`,
      (t) => `${t}.\n\nlet the debate begin.`,
      (t) => `${t}.\n\nlet the comments decide.`,
      (t) => `${t}.\n\nprove me wrong.`,
      (t) => `${t}.\n\nyou can't.`,
      (t) => `${t}.\n\ntell me why I'm wrong.`,
      (t) => `${t}.\n\ntell me one person who disagrees and why.`,
      (t) => `${t}.\n\nthe stats don't lie.`,
      (t) => `${t}.\n\nthe eye test doesn't lie.`,
      (t) => `${t}.\n\nonly the haters do.`,
      (t) => `${t}.\n\nI've studied this more than anyone I know.`,
      (t) => `${t}.\n\nit's not even close.`,
      (t) => `everyone says the opposite.\n\nbut ${t.toLowerCase()}.`,
      (t) => `most people get this backwards.\n\n${t}.`,
      (t) => `${t}.\n\nthe consensus is wrong.`,
      (t) => `${t}.\n\nthe recency bias is insane.`,
      (t) => `${t}.\n\nhere's why 👇`,
      (t) => `${t}.\n\n3 reasons:`,
      (t) => `${t}.\n\nand I can prove it.`,
      (t) => `${t}.\n\nbut nobody wants to hear it.`,
      (t) => `${t}.\n\nso I'll say it louder.`,
      (t) => `${t}.\n\nfight me on this.`,
      (t) => `${t}.\n\nthis is the hill I'll die on.`,
      (t) => `${t}.\n\nnobody can convince me otherwise.`,
      (t) => `${t}.\n\nI dare you to change my mind.`,
      (t) => `${t}.\n\nthe numbers back me up.`,
      (t) => `${t}.\n\nthe history backs me up.`,
      (t) => `${t}.\n\ncommon sense backs me up.`,
      (t) => `${t}.\n\nI used to think otherwise.`,
      (t) => `${t}.\n\nthen I actually looked at it objectively.`,
      (t) => `${t}.\n\nthe evidence is overwhelming.`,
      (t) => `${t}.\n\nI've been saying this for years.`,
      (t) => `${t}.\n\nand every year I'm more right.`,
      (t) => `${t}.\n\nthe gap is not close.`,
      (t) => `${t}.\n\nand it's getting wider.`,
      (t) => `${t}.\n\nthis isn't recency bias. this is historical fact.`,
      (t) => `${t}.\n\nI'll die on this hill.`,
      (t) => `${t}.\n\nbury me here.`,
    ],
    bodies: [
      "",
      "1. consistency\n2. impact\n3. longevity",
      "the numbers speak for themselves.",
      "the impact speaks for itself.",
      "the longevity speaks for itself.",
      "if you disagree, you're not looking at the full picture.",
      "if you disagree, you're letting emotions override facts.",
      "if you disagree, you're too young to remember.",
      "if you disagree, you're too old to see clearly.",
      "if you disagree, let's hear your argument.",
      "I've had this debate 100 times. I've won every time.",
      "not because I'm smart. because the facts are on my side.",
      "people disagree because of feelings. not facts.",
      "feelings don't change reality.",
      "I get why people disagree. I used to too.",
      "then I actually looked at the data.",
      "the data changed my mind. it'll change yours too.",
      "the eye test confirms what the stats say.",
      "you can argue stats. you can't argue what we all watched.",
      "I'm not saying this to be contrarian.",
      "I'm saying it because it's true.",
      "there's a difference.",
      "most people disagree because of nostalgia.",
      "nostalgia is not an argument.",
      "most people disagree because of recency bias.",
      "what have you done lately is not the same as what have you done overall.",
      "the full body of work matters. not just the highlight reel.",
      "when you look at the full picture, it's not close.",
      "it was never close.",
      "people just wanted it to be close.",
      "it's not.",
      "I've watched more of this than anyone I know.",
      "my opinion is informed. not popular.",
      "those are different things.",
      "the popular opinion is wrong. the informed opinion is right.",
      "they're rarely the same.",
      "I'm not saying this for engagement.",
      "I'm saying it because someone needs to.",
      "the truth is unpopular. that doesn't make it less true.",
      "I'll take truth over likes any day.",
      "if you want to debate, bring facts. not feelings.",
      "I'll wait.",
      "the debate is over. people just don't know it yet.",
      "history will prove me right.",
      "it usually does.",
      "I'm confident. not arrogant.",
      "confident means I've done the research. arrogant means I haven't.",
      "I've done the research.",
      "go check for yourself.",
      "I'll be here when you come back.",
      "with the same opinion. because the facts didn't change.",
    ],
    closers: [
      "",
      "change my mind.",
      "agree or disagree?",
      "who disagrees?",
      "let the debate begin.",
      "let the comments decide.",
      "prove me wrong.",
      "you can't.",
      "tell me why I'm wrong.",
      "I'll wait.",
      "fight me on this.",
      "this is the hill I'll die on.",
      "nobody can convince me otherwise.",
      "I dare you to change my mind.",
      "screenshot this in 6 months.",
      "the numbers back me up.",
      "the history back me up.",
      "common sense back me up.",
      "I'll die on this hill.",
      "bury me here.",
      "the debate is over.",
      "people just don't know it yet.",
      "history will prove me right.",
      "it usually does.",
      "bring facts. not feelings.",
      "I'll wait.",
      "the truth is unpopular.",
      "that doesn't make it less true.",
      "I'll take truth over likes.",
      "any day.",
      "go check for yourself.",
      "I'll be here when you come back.",
      "same opinion.",
      "because the facts didn't change.",
      "your move.",
      "the floor is yours.",
      "let's hear it.",
      "what's your argument?",
      "make it.",
      "I'm listening.",
      "but I'm not changing my mind.",
      "because I'm right.",
      "and deep down, you know it.",
      "everyone knows it.",
      "they just won't say it.",
      "so I said it.",
      "you're welcome.",
      "someone had to.",
      "it might as well be me.",
      "the truth needs a carrier.",
      "I'm volunteering.",
    ],
  },

  prediction: {
    // "X will win", "X will happen", "X is going to Y"
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nscreenshot this.`,
      (t) => `${t}.\n\nI'm putting this on the record.`,
      (t) => `${t}.\n\nnobody will believe me until it happens.`,
      (t) => `${t}.\n\nyou heard it here first.`,
      (t) => `${t}.\n\nscreenshot this in 6 months and tell me I was wrong.`,
      (t) => `hot take:\n\n${t}.`,
      (t) => `unpopular opinion:\n\n${t}.`,
      (t) => `${t}.\n\neveryone's sleeping on it.`,
      (t) => `${t}.\n\nI'm not.`,
      (t) => `${t}.\n\nmark my words.`,
      (t) => `${t}.\n\nI dare you to screenshot this and hold me to it.`,
      (t) => `${t}.\n\nmost people will laugh now and pretend they knew it later.`,
      (t) => `${t}.\n\nthe people who see it coming are already preparing.`,
      (t) => `${t}.\n\nand nobody's ready.`,
      (t) => `${t}.\n\nthis is not a hot take. this is a forecast.`,
      (t) => `${t}.\n\nI've been right about these before.`,
      (t) => `${t}.\n\nI'll be right about this one too.`,
      (t) => `${t}.\n\nthe writing is on the wall.`,
      (t) => `${t}.\n\nmost people can't read it.`,
      (t) => `${t}.\n\nI can.`,
      (t) => `${t}.\n\nthis is obvious to anyone paying attention.`,
      (t) => `${t}.\n\nbut most people aren't paying attention.`,
      (t) => `${t}.\n\nwhich is why they'll be surprised.`,
      (t) => `${t}.\n\nand I won't.`,
      (t) => `${t}.\n\nI'm calling it now.`,
      (t) => `${t}.\n\nbookmark this.`,
      (t) => `${t}.\n\nremember where you heard it.`,
      (t) => `${t}.\n\nthe trend is clear.`,
      (t) => `${t}.\n\nthe data is clear.`,
      (t) => `${t}.\n\nthe only thing unclear is why people can't see it.`,
      (t) => `${t}.\n\ndenial is powerful.`,
      (t) => `${t}.\n\nbut denial doesn't change reality.`,
      (t) => `${t}.\n\nI'm early. not wrong.`,
      (t) => `${t}.\n\nthere's a difference.`,
      (t) => `${t}.\n\nbeing early feels wrong. being right feels obvious later.`,
      (t) => `${t}.\n\nI'll feel obvious soon enough.`,
      (t) => `${t}.\n\nthe future is already here.`,
      (t) => `${t}.\n\nit's just not evenly distributed.`,
      (t) => `${t}.\n\nI can see where it's distributed.`,
      (t) => `${t}.\n\nand it's pointing one direction.`,
      (t) => `${t}.\n\nthe smart money is already moving.`,
      (t) => `${t}.\n\nthe dumb money will follow in 2 years.`,
      (t) => `${t}.\n\nand call it obvious.`,
      (t) => `${t}.\n\nit wasn't obvious. I just said it first.`,
      (t) => `${t}.\n\nthis will age well.`,
      (t) => `${t}.\n\nor I'll delete this and pretend it never happened.`,
      (t) => `${t}.\n\nbut it will age well.`,
      (t) => `${t}.\n\ntrust me.`,
    ],
    bodies: [
      "",
      "the signs are everywhere if you're looking.",
      "the trajectory is clear.",
      "the momentum is building.",
      "the pieces are already in place.",
      "you just have to connect them.",
      "most people can't see patterns until they're complete.",
      "I see them while they're forming.",
      "that's the difference.",
      "I'm not guessing. I'm extrapolating.",
      "extrapolation is just pattern recognition applied to the future.",
      "and the pattern is clear.",
      "every trend points to this.",
      "every data point confirms it.",
      "every signal is flashing.",
      "the question isn't if. it's when.",
      "and 'when' is sooner than people think.",
      "people always underestimate how fast things change.",
      "they overestimate the short term and underestimate the long term.",
      "I'm doing the opposite.",
      "the consensus is always wrong at the turning points.",
      "and we're at a turning point.",
      "the consensus hasn't figured it out yet.",
      "they will. when it's obvious.",
      "but by then, it'll be too late.",
      "the early ones win. the late ones watch.",
      "I'm planning to win.",
      "I've been tracking this for months.",
      "every data point confirms the direction.",
      "every conversation with insiders confirms it.",
      "every market signal points the same way.",
      "when everything points one direction, bet that direction.",
      "I'm betting.",
      "I'm not saying I have special information.",
      "I'm saying I'm paying attention.",
      "most people aren't.",
      "that's the edge.",
      "attention is the only edge that matters.",
      "and I'm paying it.",
      "the future doesn't announce itself.",
      "it arrives quietly. then everyone pretends they saw it coming.",
      "I saw it coming. and I said it.",
      "right here. right now.",
      "the people who are laughing now will be copying later.",
      "that's how it always works.",
      "first they laugh. then they deny. then they adopt.",
      "we're in the laughing phase.",
      "I'll see you in the adopting phase.",
      "I'll be there first.",
      "as always.",
    ],
    closers: [
      "",
      "screenshot this.",
      "screenshot this in 6 months.",
      "mark my words.",
      "I'm putting this on the record.",
      "you heard it here first.",
      "remember where you heard it.",
      "bookmark this.",
      "I'm calling it now.",
      "the writing is on the wall.",
      "the trend is clear.",
      "the data is clear.",
      "I'm early. not wrong.",
      "this will age well.",
      "trust me.",
      "I dare you to hold me to it.",
      "screenshot and hold me to it.",
      "most people will laugh now.",
      "and pretend they knew it later.",
      "the people who see it coming are already preparing.",
      "are you?",
      "the smart money is already moving.",
      "the dumb money will follow.",
      "in 2 years.",
      "and call it obvious.",
      "it wasn't obvious.",
      "I just said it first.",
      "first they laugh.",
      "then they deny.",
      "then they adopt.",
      "we're in the laughing phase.",
      "see you in the adopting phase.",
      "I'll be there first.",
      "the future doesn't announce itself.",
      "it arrives quietly.",
      "then everyone pretends they saw it coming.",
      "I saw it coming.",
      "and I said it.",
      "right here.",
      "right now.",
      "the question isn't if.",
      "it's when.",
      "and when is sooner than you think.",
      "I'm not guessing.",
      "I'm extrapolating.",
      "the pattern is clear.",
      "bet accordingly.",
      "or don't.",
      "but don't say I didn't tell you.",
      "because I did.",
      "right here.",
    ],
  },

  product: {
    // "X gives you Y", "a SaaS that does Z"
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nand nobody's talking about it.`,
      (t) => `${t}.\n\nmost people are still doing this manually.`,
      (t) => `${t}.\n\nthe people who figured this out first are way ahead.`,
      (t) => `${t}.\n\neveryone's sleeping on this.`,
      (t) => `${t}.\n\nif you're not using it yet, you're losing time.`,
      (t) => `${t}.\n\nthat's insane.`,
      (t) => `${t}.\n\nand it's only getting better.`,
      (t) => `here's the thing about ${t.split(/\s+/)[0].toLowerCase()}:`,
      (t) => `${t}.\n\nI tried it for a week.`,
      (t) => `${t}.\n\nI'm not going back.`,
      (t) => `${t}.\n\nthe gap is only getting wider.`,
      (t) => `${t}.\n\nstop doing this manually.`,
      (t) => `${t}.\n\nyour competitors are already using it.`,
      (t) => `${t}.\n\nthe question isn't if you'll use it. it's when.`,
      (t) => `${t}.\n\nand when is now.`,
      (t) => `${t}.\n\nbefore: hours of manual work.`,
      (t) => `${t}.\n\nafter: seconds.`,
      (t) => `${t}.\n\n3 hours → 20 minutes.`,
      (t) => `${t}.\n\nquality stays the same. time doesn't.`,
      (t) => `${t}.\n\ntime is the only thing you can't make more of.`,
      (t) => `${t}.\n\nstop romanticizing the hard way.`,
      (t) => `${t}.\n\nthe hard way isn't noble. it's just slow.`,
      (t) => `${t}.\n\neveryone complains about not having enough time.`,
      (t) => `${t}.\n\nthen spends hours doing something this does in seconds.`,
      (t) => `${t}.\n\nthe bottleneck isn't time. it's willingness to change.`,
      (t) => `${t}.\n\nI used to do this manually.`,
      (t) => `${t}.\n\nI can't imagine going back.`,
      (t) => `${t}.\n\nthe output is better. the time is less.`,
      (t) => `${t}.\n\nthat's the part nobody believes until they try it.`,
      (t) => `${t}.\n\nso try it.`,
      (t) => `${t}.\n\nnobody talks about it enough.`,
      (t) => `${t}.\n\nbut the boring tools that save you time? those matter.`,
      (t) => `${t}.\n\neveryone wants the flashy tool.`,
      (t) => `${t}.\n\nthis isn't flashy. but it works.`,
      (t) => `${t}.\n\nand that's what counts.`,
      (t) => `${t}.\n\nI stopped doing this manually.`,
      (t) => `${t}.\n\nstarted using this.`,
      (t) => `${t}.\n\nsaved hours this week alone.`,
      (t) => `${t}.\n\nthe tool isn't the flex. the time is.`,
      (t) => `${t}.\n\n90% less time. same quality. zero manual work.`,
      (t) => `${t}.\n\ncut my workflow from hours to minutes.`,
      (t) => `${t}.\n\nthe output is better.`,
      (t) => `${t}.\n\nthat's the part nobody believes.`,
      (t) => `${t}.\n\nuntil they try it.`,
      (t) => `${t}.\n\nrefusing to use it isn't dedication. it's stubbornness.`,
      (t) => `${t}.\n\nthe people who adopt early have a massive head start.`,
      (t) => `${t}.\n\nthat head start compounds.`,
      (t) => `${t}.\n\nevery day you wait is a day you lose.`,
    ],
    bodies: [
      "",
      "I was skeptical at first.",
      "then I tried it.",
      "now I can't imagine working without it.",
      "the time savings alone are worth it.",
      "but the quality improvement is the real surprise.",
      "it's not just faster. it's better.",
      "that's the part nobody talks about.",
      "everyone focuses on speed. nobody talks about quality.",
      "the quality is what makes it a no-brainer.",
      "I've tried every tool in this space.",
      "none of them come close.",
      "I'm not exaggerating.",
      "the gap between this and the alternatives is massive.",
      "most tools do one thing well. this does everything well.",
      "I was doing this manually for years.",
      "years. wasted. on something that takes seconds now.",
      "I can't get that time back.",
      "but I can stop wasting more.",
      "so I did.",
      "the ROI is immediate.",
      "not in months. in the first hour.",
      "by hour 2, I'd already saved more time than it took to set up.",
      "by the end of the week, it paid for itself 10x over.",
      "I'm not paid to say this. I'm saying it because it's true.",
      "when I find something good, I share it.",
      "this is me sharing.",
      "the people who ignore this will be doing it manually in 2 years.",
      "the people who adopt it now will be 2 years ahead.",
      "that gap is insurmountable.",
      "I'm on the right side of that gap.",
      "you should be too.",
      "the tools you use determine the speed you move.",
      "this tool makes you move fast.",
      "faster than the competition.",
      "that's not a feature. that's an advantage.",
      "and advantages compound.",
      "the best investment I made this year wasn't a course or a book.",
      "it was switching to this.",
      "the ROI dwarfs everything else.",
      "I tell everyone about it.",
      "some people listen. some don't.",
      "the ones who listen are ahead now.",
      "the ones who don't are still doing it manually.",
      "I wonder which group they'd rather be in.",
      "the shift from manual to automated is not optional.",
      "it's inevitable.",
      "the only question is whether you're early or late.",
      "early costs a little adjustment. late costs a lot of time.",
      "I chose early.",
      "you should too.",
      // Outcome-focused bodies — what the user gets
      "the outcome: 4 hours saved every single week. that's 200+ hours a year.",
      "the outcome: shipping content the same day you record it.",
      "the outcome: turning one recording into 5 pieces of content automatically.",
      "the outcome: never paying for basic editing cleanup again.",
      "the outcome: posting consistently without burning out.",
      "the outcome: spending your time on story, not on mechanical cuts.",
      "the outcome: a workflow that scales without hiring.",
      "the outcome: going from idea to published in minutes, not days.",
      "the outcome: captions, clips, and cleanup in one pass.",
      "the outcome: your creative energy goes where it should — not into busywork.",
      "the outcome: a folder of 'recorded but never edited' that's finally empty.",
      "the outcome: posting weekly without dreading the edit.",
      "the outcome: a first draft in seconds. final cut in minutes.",
      "the outcome: more output. less effort. same quality.",
      "the outcome: the boring part disappears. the creative part is all that's left.",
      "the outcome: you still have final say. you just skip the part you hate.",
      "the outcome: time back. that's it. that's the whole value proposition.",
      "the outcome: a workflow that compounds — every week gets faster.",
      "the outcome: never starting from a blank timeline again.",
      "the outcome: your competition can't keep up because they're still doing it manually.",
    ],
    closers: [
      "",
      "stop doing this manually.",
      "your competitors already switched.",
      "the gap is only getting wider.",
      "every day you wait is a day you lose.",
      "try it. you won't go back.",
      "I dare you to try it for a week.",
      "the ROI is immediate.",
      "it pays for itself in the first hour.",
      "I'm not paid to say this.",
      "I just can't not share it.",
      "when something is this good, you tell people.",
      "so I'm telling you.",
      "the people who ignore this will regret it.",
      "not today. but soon.",
      "the shift is happening.",
      "with or without you.",
      "I'd rather be early.",
      "you should too.",
      "stop romanticizing the hard way.",
      "the hard way isn't noble. it's just slow.",
      "and slow doesn't win.",
      "fast does.",
      "this is fast.",
      "try it.",
      "do it.",
      "today.",
      "not tomorrow.",
      "today.",
      "your future self will thank you.",
      "or your future self will be doing it manually.",
      "your choice.",
      "I made mine.",
      "best decision I made this year.",
      "the tools you use determine the speed you move.",
      "this makes you fast.",
      "choose wisely.",
      "or don't. but don't say I didn't warn you.",
      "the shift is inevitable.",
      "be early.",
      "the early ones win.",
      "the late ones watch.",
      "I'm planning to win.",
      "are you?",
      "try it for a week.",
      "if you hate it, stop.",
      "you won't hate it.",
      "nobody does.",
      "once you try it, manual feels insane.",
      "because it is.",
      "stop.",
    ],
  },

  statement: {
    // General claims, "X is Y", fallback
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nI said what I said.`,
      (t) => `${t}.\n\nand most people won't admit it.`,
      (t) => `${t}.\n\neveryone knows it. nobody says it.`,
      (t) => `${t}.\n\nthat's it. that's the post.`,
      (t) => `${t}.\n\nand I'm tired of pretending it's not true.`,
      (t) => `${t}.\n\nnobody wants to hear it but it's facts.`,
      (t) => `unpopular opinion:\n\n${t}.`,
      (t) => `hot take:\n\n${t}.`,
      (t) => `${t}.\n\nwho disagrees?`,
      (t) => `${t}.\n\nlet's debate.`,
      (t) => `${t}.\n\nlet the comments decide.`,
      (t) => `${t}.\n\nprove me wrong.`,
      (t) => `${t}.\n\nyou can't.`,
      (t) => `${t}.\n\ntell me why I'm wrong.`,
      (t) => `${t}.\n\nI'll wait.`,
      (t) => `${t}.\n\ntell me one person who disagrees and why.`,
      (t) => `nobody talks about this enough.\n\n${t}.`,
      (t) => `${t}.\n\nthe people who understand this are already ahead.`,
      (t) => `${t}.\n\nI've been saying this for years.`,
      (t) => `everyone disagrees with this.\n\n${t}.`,
      (t) => `most people think the opposite.\n\n${t}.`,
      (t) => `everyone's scared to say it.\n\n${t}.`,
      (t) => `${t}.\n\nso I'll say it.`,
      (t) => `${t}.\n\nthe gap between what's popular and what's true is insane.`,
      (t) => `${t}.\n\nthe consensus is wrong.`,
      (t) => `${t}.\n\nand I'm not afraid to say it.`,
      (t) => `${t}.\n\nsomeone had to.`,
      (t) => `${t}.\n\nmight as well be me.`,
      (t) => `${t}.\n\nthe truth needs a carrier.`,
      (t) => `${t}.\n\nI'm volunteering.`,
      (t) => `${t}.\n\nthis is not a popular opinion.`,
      (t) => `${t}.\n\nit's a correct one.`,
      (t) => `${t}.\n\nthose are different things.`,
      (t) => `${t}.\n\nI used to think otherwise.`,
      (t) => `${t}.\n\nthen I actually looked into it.`,
      (t) => `${t}.\n\nthe evidence changed my mind.`,
      (t) => `${t}.\n\nit'll change yours too.`,
      (t) => `${t}.\n\nif you let it.`,
      (t) => `${t}.\n\nmost people won't.`,
      (t) => `${t}.\n\nand that's fine.`,
      (t) => `${t}.\n\nthe truth doesn't need everyone to agree.`,
      (t) => `${t}.\n\nit just needs to be true.`,
      (t) => `${t}.\n\nand it is.`,
      (t) => `${t}.\n\nwhether you like it or not.`,
      (t) => `${t}.\n\nI'm not saying this for likes.`,
      (t) => `${t}.\n\nI'm saying it because it needs to be said.`,
      (t) => `${t}.\n\nand nobody else is saying it.`,
      (t) => `${t}.\n\nso here I am.`,
      (t) => `${t}.\n\nsaying it.`,
    ],
    bodies: [
      "",
      "I'm not being contrarian for the sake of it.",
      "I genuinely believe this.",
      "and I have reasons.",
      "good ones.",
      "if you disagree, I respect that.",
      "but let's hear your argument.",
      "I've had this debate many times.",
      "I've never lost.",
      "not because I'm smart. because I'm right.",
      "the truth is often unpopular.",
      "that doesn't make it less true.",
      "I'll take truth over popularity any day.",
      "most people disagree because of feelings.",
      "feelings don't change facts.",
      "I get why people resist this.",
      "it challenges what they want to believe.",
      "but wanting something to be false doesn't make it false.",
      "I've looked at this from every angle.",
      "the conclusion is the same.",
      "every time.",
      "I'm confident in this. not arrogant.",
      "confident means I've done the work. arrogant means I haven't.",
      "I've done the work.",
      "go check for yourself.",
      "I'll be here when you come back.",
      "with the same opinion.",
      "because the facts didn't change.",
      "I'm not asking you to agree.",
      "I'm asking you to think.",
      "actually think. not react.",
      "there's a difference.",
      "most people react. few people think.",
      "the ones who think usually end up here.",
      "same place I am.",
      "on the right side of this.",
      "the popular opinion is comfortable.",
      "the right opinion is not.",
      "I chose right over comfortable.",
      "you should too.",
      "it's not fun. but it's honest.",
      "and honest is better than comfortable.",
      "always.",
      "I know this post will get pushback.",
      "I don't care.",
      "the truth is more important than engagement.",
      "and this is the truth.",
      "whether you're ready for it or not.",
      "some people will unfollow over this.",
      "good. the truth filters your audience.",
      "I'd rather have 100 followers who can handle truth than 10,000 who can't.",
      "quality over quantity.",
    ],
    closers: [
      "",
      "change my mind.",
      "agree or disagree?",
      "who disagrees?",
      "let's debate.",
      "let the comments decide.",
      "prove me wrong.",
      "you can't.",
      "tell me why I'm wrong.",
      "I'll wait.",
      "I said what I said.",
      "that's it. that's the post.",
      "the truth doesn't need your agreement.",
      "it just needs to be true.",
      "and it is.",
      "whether you like it or not.",
      "I'm not asking you to agree.",
      "I'm asking you to think.",
      "actually think.",
      "the popular opinion is comfortable.",
      "the right opinion is not.",
      "I chose right.",
      "you should too.",
      "it's not fun. but it's honest.",
      "and honest > comfortable.",
      "always.",
      "I know this gets pushback.",
      "I don't care.",
      "truth > engagement.",
      "always.",
      "some people will unfollow.",
      "good.",
      "the truth filters your audience.",
      "I'd rather have 100 who can handle it than 10,000 who can't.",
      "quality over quantity.",
      "the truth is unpopular.",
      "that doesn't make it less true.",
      "I'll take truth over likes.",
      "any day.",
      "go check for yourself.",
      "I'll be here when you come back.",
      "same opinion.",
      "because the facts didn't change.",
      "your move.",
      "the floor is yours.",
      "what's your argument?",
      "make it.",
      "I'm listening.",
      "but I'm not changing my mind.",
      "because I'm right.",
    ],
  },

  milestone_localbusiness: {
    // "I opened a new restaurant", "I started a cafe", "I launched a food truck"
    // Physical/local business — NOT software. No "building in public", no MRR, no SaaS language.
    hooks: [
      (t) => `${t}.`,
      (t) => `${t}.\n\nthe doors are open.`,
      (t) => `${t}.\n\nand I'm terrified.`,
      (t) => `${t}.\n\nthis has been a dream for years.`,
      (t) => `${t}.\n\nI can't believe it's real.`,
      (t) => `${t}.\n\nsurreal moment.`,
      (t) => `${t}.\n\nI've been planning this for years.`,
      (t) => `${t}.\n\nthe buildout took forever.`,
      (t) => `${t}.\n\nso many permits. so many delays. but we're here.`,
      (t) => `${t}.\n\nmy hands are shaking typing this.`,
      (t) => `${t}.\n\nI almost gave up a hundred times.`,
      (t) => `${t}.\n\nbut I didn't.`,
      (t) => `${t}.\n\nthis is the scariest thing I've ever done.`,
      (t) => `${t}.\n\nand the most exciting.`,
      (t) => `${t}.\n\nno investors. no partners. just me.`,
      (t) => `${t}.\n\nI put everything into this.`,
      (t) => `${t}.\n\nevery penny. every hour. every ounce of energy.`,
      (t) => `${t}.\n\nif this fails, I lose a lot.`,
      (t) => `${t}.\n\nbut if it works, I built something real.`,
      (t) => `${t}.\n\nsomething physical. something people can touch.`,
      (t) => `${t}.\n\nsomething my city can be proud of.`,
      (t) => `${t}.\n\nI'm not building an app. I'm building a place.`,
      (t) => `${t}.\n\na place where people will eat, laugh, celebrate.`,
      (t) => `${t}.\n\nthat's the dream.`,
      (t) => `${t}.\n\nand today it starts.`,
      (t) => `${t}.\n\nmy family thinks I'm crazy.`,
      (t) => `${t}.\n\nmy friends think I'm brave.`,
      (t) => `${t}.\n\nI think I'm both.`,
      (t) => `${t}.\n\nthe lease is signed. the keys are in my hand.`,
      (t) => `${t}.\n\nthere's no going back now.`,
      (t) => `${t}.\n\nI've been working on this in secret for months.`,
      (t) => `${t}.\n\nand now it's not a secret anymore.`,
      (t) => `${t}.\n\nthe sign is up. the lights are on.`,
      (t) => `${t}.\n\nwe open to the public today.`,
      (t) => `${t}.\n\nfirst customer walked in. I almost cried.`,
      (t) => `${t}.\n\nI've served hundreds of people today.`,
      (t) => `${t}.\n\nevery one of them felt like a victory.`,
      (t) => `${t}.\n\nthe reviews are starting to come in.`,
      (t) => `${t}.\n\nand I'm refreshing my phone every 5 minutes.`,
      (t) => `${t}.\n\nthe first day is done. my feet are destroyed.`,
      (t) => `${t}.\n\nbut my heart is full.`,
      (t) => `${t}.\n\nI'm exhausted. I'm proud. I'm open.`,
      (t) => `${t}.\n\nthis is the beginning of something.`,
      (t) => `${t}.\n\nI don't know what yet. but I can feel it.`,
      (t) => `${t}.\n\nthe neighborhood is going to change.`,
      (t) => `${t}.\n\nat least that's the plan.`,
      (t) => `${t}.\n\nI'm betting on this community.`,
      (t) => `${t}.\n\nand I'm betting on myself.`,
      (t) => `${t}.\n\nlet's do this.`,
    ],
    bodies: [
      "",
      "people told me I was crazy to open a physical business in this economy.",
      "maybe they're right. but I'd rather try than wonder.",
      "the margins are tight. the hours are brutal. the risk is real.",
      "and I'm doing it anyway.",
      "this isn't a side project. this is my life now.",
      "every detail matters. the menu. the lighting. the music. the welcome.",
      "I've obsessed over all of it.",
      "because the first impression is the only one that matters in this game.",
      "you get one chance to make someone a regular.",
      "I'm not wasting it.",
      "the recipe has been tested 100 times.",
      "the space has been designed to feel like home.",
      "the team has been trained to care like I care.",
      "the rest is up to the customers.",
      "I've worked in this industry for years. I've seen what works.",
      "now I'm doing it my way.",
      "the way I always thought it should be done.",
      "no corporate playbook. no franchise manual. just instinct and care.",
      "I'm scared of the numbers. rent, payroll, inventory, taxes.",
      "it's a lot. it's real. it doesn't stop.",
      "but neither do I.",
      "the first month will make or break us.",
      "everyone says the first year is the hardest.",
      "I believe them. but I'm ready for hard.",
      "I've been saving for this for 5 years.",
      "every dollar I earned went into this dream.",
      "now the dream is a lease and a menu and a team.",
      "it's less glamorous than it sounds. and more real.",
      "I'm not trying to be the next big chain.",
      "I'm trying to be the best spot in the neighborhood.",
      "that's the whole goal.",
      "if the neighborhood loves it, we survive.",
      "if they don't, we learn and we adapt.",
      "but we don't quit.",
      "I've seen too many places open with hype and close within a year.",
      "I'm playing the long game.",
      "consistency over hype. regulars over virality.",
      "that's the strategy.",
      "the food is good. the space is warm. the welcome is genuine.",
      "the rest is just showing up every day.",
      "I'll be here every day.",
      "open to close. every shift. every day. for as long as it takes.",
      "that's the commitment.",
      "if you're in the area, come say hi.",
      "first drink/meal is on me.",
      "I want to meet the people who make this work.",
      "because this isn't just my dream. it's ours.",
      "mine and the neighborhood's.",
      "let's build something together.",
    ],
    closers: [
      "",
      "come say hi.",
      "first one's on me.",
      "we're open.",
      "the doors are open.",
      "come hungry.",
      "see you soon.",
      "the welcome is warm.",
      "stop by.",
      "we're ready for you.",
      "the menu is set. the team is ready.",
      "let's do this.",
      "day 1.",
      "day 1 of many.",
      "here we go.",
      "let's go.",
      "wish me luck.",
      "I'll need it.",
      "but I'm ready.",
      "the hard part starts now.",
      "the real work begins.",
      "this is just the beginning.",
      "the best is yet to come.",
      "if you're local, come through.",
      "I'd love to meet you.",
      "tag someone who should know.",
      "share with a friend who lives nearby.",
      "the more the merrier.",
      "we're in this together.",
      "this is our spot now.",
      "I'm betting on this neighborhood.",
      "and I'm betting on myself.",
      "let's see how far we can take this.",
      "one customer at a time.",
      "one regular at a time.",
      "one day at a time.",
      "brick by brick.",
      "the foundation is laid.",
      "now we build.",
      "thank you to everyone who supported.",
      "now come eat.",
      "the stove is on.",
      "the doors are unlocked.",
      "we're ready.",
      "come in.",
      "we've been waiting for you.",
      "this is your place too.",
      "welcome home.",
      "see you at the table.",
    ],
  },
};

// ---------------------------------------------------------------------------
// Seeded random — ensures same topic never produces same posts
// ---------------------------------------------------------------------------

function seededRandom(seed) {
  let s = seed;
  return function() {
    s = (s * 9301 + 49297) % 233280;
    return s / 233280;
  };
}

function pickWithRand(arr, rand) {
  return arr[Math.floor(rand() * arr.length)];
}

// ---------------------------------------------------------------------------
// Generate posts from a topic using the compositional system
// ---------------------------------------------------------------------------

function generateCompositional(topic, contextType, count = 5, seed = null) {
  const ctx = CONTEXTS[contextType] || CONTEXTS.statement;
  const rand = seededRandom(seed || (Date.now() + Math.floor(Math.random() * 1000000)));

  const hooks = ctx.hooks;
  const bodies = ctx.bodies;
  const closers = ctx.closers;

  // Generate a large pool by combining hooks × bodies × closers
  // We sample randomly from the combinatorial space
  const pool = [];
  const seen = new Set();
  const targetPoolSize = Math.min(count * 10, hooks.length * bodies.length * closers.length);

  let attempts = 0;
  while (pool.length < targetPoolSize && attempts < targetPoolSize * 3) {
    attempts++;
    const hook = pickWithRand(hooks, rand)(topic);
    const body = pickWithRand(bodies, rand);
    const closer = pickWithRand(closers, rand);

    // Build the post text
    let text = hook;
    if (body) text += "\n\n" + body;
    if (closer) text += "\n\n" + closer;

    // Dedup within pool
    const key = text.toLowerCase().slice(0, 80);
    if (!seen.has(key)) {
      seen.add(key);
      pool.push({ text, type: contextType.includes("milestone") ? "founder_story" : contextType === "opinion" || contextType === "prediction" || contextType === "statement" ? "contrarian" : "contrarian" });
    }
  }

  return pool;
}

// ---------------------------------------------------------------------------
// Get list of available context types
// ---------------------------------------------------------------------------

function getContextTypes() {
  return Object.keys(CONTEXTS);
}

// ---------------------------------------------------------------------------
// Count total unique combinations possible
// ---------------------------------------------------------------------------

function countCombinations() {
  const counts = {};
  let total = 0;
  for (const [name, ctx] of Object.entries(CONTEXTS)) {
    const combos = ctx.hooks.length * ctx.bodies.length * ctx.closers.length;
    counts[name] = combos;
    total += combos;
  }
  return { perContext: counts, total };
}

module.exports = {
  CONTEXTS,
  generateCompositional,
  getContextTypes,
  countCombinations,
  seededRandom,
};
